# TASKS

In [ ]:
# Create House Prices CSV + Apply RFE

import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

# -------------------------------
# Create Sample House Prices Data
# -------------------------------

data = {
    "OverallQual":[7,6,7,7,8,5,8,7,7,5,6,8,9,4,5],
    "GrLivArea":[1710,1262,1786,1717,2198,1362,1694,2090,1774,1077,1500,2400,2800,900,1200],
    "GarageCars":[2,2,2,3,3,2,2,2,2,1,2,3,3,1,2],
    "TotalBsmtSF":[856,1262,920,756,1145,796,1686,1107,952,991,850,1500,1700,700,820],
    "YearBuilt":[2003,1976,2001,1915,2000,1993,2004,1973,1931,1939,1985,2010,2015,1950,1965],
    "LotArea":[8450,9600,11250,9550,14260,14115,10084,10382,6120,7420,8500,12000,15000,7000,8200],
    "BedroomAbvGr":[3,3,3,3,4,3,3,4,2,2,3,4,5,2,3],
    "FullBath":[2,2,2,1,2,1,2,2,1,1,2,3,3,1,2],
    "SalePrice":[208500,181500,223500,140000,250000,143000,307000,200000,129900,118000,
                 180000,320000,400000,100000,150000]
}

df = pd.DataFrame(data)

# Save CSV
df.to_csv("train.csv", index=False)

print("CSV file created successfully!")

# -------------------------------
# Read CSV
# -------------------------------

house = pd.read_csv("train.csv")

print("\nFirst 5 Rows")
print(house.head())

# -------------------------------
# Features and Target
# -------------------------------

X = house.drop("SalePrice", axis=1)
y = house["SalePrice"]

# -------------------------------
# Linear Regression Model
# -------------------------------

model = LinearRegression()

# -------------------------------
# Recursive Feature Elimination
# -------------------------------

selector = RFE(
    estimator=model,
    n_features_to_select=5
)

selector.fit(X, y)

# -------------------------------
# Selected Features
# -------------------------------

selected = X.columns[selector.support_]

print("\nTop 5 Selected Features")
print(selected.tolist())

CSV file created successfully!

First 5 Rows
   OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  LotArea  \
0            7       1710           2          856       2003     8450   
1            6       1262           2         1262       1976     9600   
2            7       1786           2          920       2001    11250   
3            7       1717           3          756       1915     9550   
4            8       2198           3         1145       2000    14260   

   BedroomAbvGr  FullBath  SalePrice  
0             3         2     208500  
1             3         2     181500  
2             3         2     223500  
3             3         1     140000  
4             4         2     250000  

Top 5 Selected Features
['OverallQual', 'GarageCars', 'YearBuilt', 'BedroomAbvGr', 'FullBath']


In [3]:
#Create Polynomial Features (Degree = 2)
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# Sample Data
X = np.array([
    [2,3],
    [4,5],
    [6,7]
])

# Polynomial Features
poly = PolynomialFeatures(
    degree=2,
    include_bias=False
)

X_poly = poly.fit_transform(X)

print("Original Shape:", X.shape)
print("New Shape:", X_poly.shape)

print("\nPolynomial Features")
print(X_poly)

Original Shape: (3, 2)
New Shape: (3, 5)

Polynomial Features
[[ 2.  3.  4.  6.  9.]
 [ 4.  5. 16. 20. 25.]
 [ 6.  7. 36. 42. 49.]]


In [6]:
#Build a Full Pipeline
from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

# Load Dataset
data = load_breast_cancer()

X = data.data
y = data.target

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Pipeline
pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=5000))
])

# Train
pipeline.fit(X_train, y_train)

# Accuracy
accuracy = pipeline.score(X_test, y_test)

print("Accuracy =", accuracy)

Accuracy = 0.9736842105263158


In [7]:
#Apply ColumnTransformer for Numeric and Categorical Columns
import pandas as pd

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

# Sample Dataset
df = pd.DataFrame({
    "Age":[22,35,28,40],
    "Salary":[25000,50000,40000,60000],
    "Gender":["Male","Female","Male","Female"],
    "City":["Delhi","Mumbai","Delhi","Chennai"]
})

# Numeric Columns
numeric_features = [
    "Age",
    "Salary"
]

# Categorical Columns
categorical_features = [
    "Gender",
    "City"
]

# Column Transformer
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numeric_features
        ),
        (
            "cat",
            OneHotEncoder(),
            categorical_features
        )
    ]
)

# Transform Data
transformed = preprocessor.fit_transform(df)

print(transformed)

[[-1.35375921 -1.45010473  0.          1.          0.          1.
   0.        ]
 [ 0.5488213   0.48336824  1.          0.          0.          0.
   1.        ]
 [-0.47564513 -0.29002095  0.          1.          0.          1.
   0.        ]
 [ 1.28058303  1.25675744  1.          0.          1.          0.
   0.        ]]


# PRACTICE

In [ ]:
# Create Titanic CSV + End-to-End Pipeline

import pandas as pd

# -----------------------------
# Create Titanic Dataset
# -----------------------------

data = {
    "Pclass":[3,1,3,1,3,2,1,3,2,1,3,2,1,3,1],
    "Sex":["male","female","female","female","male",
           "male","female","male","female","male",
           "female","male","female","male","female"],
    "Age":[22,38,26,35,35,28,54,2,27,14,30,40,45,20,36],
    "Fare":[7.25,71.28,7.92,53.10,8.05,
            13.00,51.86,21.07,11.13,30.07,
            7.75,15.50,83.15,8.45,52.00],
    "Embarked":["S","C","S","S","S",
                "Q","S","S","C","C",
                "Q","S","S","S","C"],
    "Survived":[0,1,1,1,0,
                0,1,1,1,1,
                0,0,1,0,1]
}

df = pd.DataFrame(data)

# Save CSV
df.to_csv("titanic.csv", index=False)

print("CSV file 'titanic.csv' created successfully!")

# -----------------------------
# Read CSV
# -----------------------------

df = pd.read_csv("titanic.csv")

print(df.head())

# -----------------------------
# Features & Target
# -----------------------------

X = df.drop("Survived", axis=1)
y = df["Survived"]

# -----------------------------
# Train-Test Split
# -----------------------------

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -----------------------------
# Preprocessing
# -----------------------------

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

numeric_features = ["Age","Fare"]

categorical_features = ["Sex","Embarked","Pclass"]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

# -----------------------------
# Random Forest Pipeline
# -----------------------------

from sklearn.ensemble import RandomForestClassifier

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

print("\nAccuracy =", accuracy)

CSV file 'titanic.csv' created successfully!
   Pclass     Sex  Age   Fare Embarked  Survived
0       3    male   22   7.25        S         0
1       1  female   38  71.28        C         1
2       3  female   26   7.92        S         1
3       1  female   35  53.10        S         1
4       3    male   35   8.05        S         0

Accuracy = 1.0


In [10]:
#Feature Engineering Challenge
import pandas as pd

# Read Titanic CSV
df = pd.read_csv("titanic.csv")

# --------------------------
# Feature Engineering
# --------------------------

# 1. Child or Adult
df["IsChild"] = (df["Age"] < 16).astype(int)

# 2. High Fare Passenger
df["HighFare"] = (df["Fare"] > df["Fare"].median()).astype(int)

# 3. Female Passenger
df["IsFemale"] = (df["Sex"] == "female").astype(int)

print(df.head())

   Pclass     Sex  Age   Fare Embarked  Survived  IsChild  HighFare  IsFemale
0       3    male   22   7.25        S         0        0         0         0
1       1  female   38  71.28        C         1        0         1         1
2       3  female   26   7.92        S         1        0         0         1
3       1  female   35  53.10        S         1        0         1         1
4       3    male   35   8.05        S         0        0         0         0
